version: '3.4'

services:
  pg:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: 123

  app:
    build:
      context: .
      target: sibrowser_base
    environment:
      PG_HOST: pg
      PG_USERNAME: postgres
      PGPASSWORD: 123
      VK_APP_ID:
      VK_SECRET:
      VK_SERVICE:
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis:6379
      ADMIN_LOGIN: admin
      ADMIN_PASSWORD: admin
      HEROKU_TOKEN:
      HEROKU_APP_NAME:

    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
    depends_on:
      - pg
    command: /bin/bash
    ports:
      - '3000:3000'

  redis:
    image: redis:6.2.3
