version: '3.4'

services:
  pg:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ../sibrowser_data/pg:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: sibrowser_base
    environment:
      PG_HOST: pg
      PG_USERNAME: postgres
      PG_PASSWORD: 123
      VK_APP_ID:
      VK_SECRET:
      VK_SERVICE:
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis:6379

    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    depends_on:
      - pg
    command: /bin/bash
    ports:
      - '3000:3000'

  redis:
    image: redis:4

volumes:
  bundle:
