default: &default
  adapter: redis
  url: <%= ENV['REDIS_PROVIDER'] ? ENV[ENV["REDIS_PROVIDER"]] : 'set_redis_in_cable.yml' %>

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
  channel_prefix: sibrowser_production
